version: "3.9"

services:
  breast-cancer-api:
    build:
      context: .
      dockerfile: dockerfile
    image: harshshekar812/breast-cancer-api:v1
    container_name: breast-cancer-api
    ports:
      - "4000:4000"
    environment:
      MODEL_PATH: "breast_model.pkl"
      MODEL_VERSION: "v1"
      APP_PORT: 4000
    volumes:
      - ./outputs:/app/outputs
    restart: unless-stopped
